[Solved] - Do not trigger transactions on the wrong network
gnosis/tabula pull request #126
Opened 2022-06-24 18:17 UTC by juliopavila

closed #100 

Record:

https://user-images.githubusercontent.com/19823989/175619496-a8613adc-e677-4766-bcec-79d99e95aea4.mov

2022-06-24 23:40 UTC, auryn-macmillan commented
It would be good if the toast mentioned which network to switch to. Something like `Wrong network. Please switch to {network name}.`.

2022-06-27 16:03 UTC, manboy-eth requested changes
In my view, the cleanest solution to this is: always disconnecting the wallet when the user changes the network.

This is already implemented. However, there is a bug that makes the wallet not disconnect when we change to `Mainnet`.
I think fixing this bug should solve the #100.

Since it is not possible to connect a wallet to the "wrong network", it should not be possible to reach a state where a transaction can be executed on the wrong network.

2022-06-28 08:13 UTC, manboy-eth commented on packages/app/src/utils/validation.ts
> +export const checkIsValidChain = (currentChain: number): boolean => {
If we are not in a publication, it should return `true` as long as we are connected to one of the supported chains.

If not, it fails when creating a new publication,

2022-06-28 08:28 UTC, manboy-eth commented
> In my view, the cleanest solution to this is: always disconnecting the wallet when the user changes the network.
> 
> This is already implemented. However, there is a bug that makes the wallet not disconnect when we change to `Mainnet`. I think fixing this bug should solve the #100.
> 
> Since it is not possible to connect a wallet to the "wrong network", it should not be possible to reach a state where a transaction can be executed on the wrong network.

I was wrong in my assumption, sorry. It seems that as long as you switch to a wallet that has already been connected to Tabula, it will not disconnect the wallet.

I still think disconnecting the wallet whenever the network changes might be the best solution.
Since there are already checks for the network/chain when connecting a wallet, it might solve the problem (instead of having two independent "chain validation solutions"). See: https://github.com/gnosis/tabula/blob/2a690668c1210b30e6554de58cd6053e6f6d4757/packages/app/src/components/views/wallet/WalletView.tsx#L64

Perhaps there is another reason we want users to be able to change between networks without disconnecting the wallet?

2022-06-30 10:51 UTC, manboy-eth approved these changes
LGTM

2022-06-30 12:20 UTC, merged