Design updates
gnosis/tabula pull request #202
Opened 2023-01-25 20:22 UTC by cedricwaxwing

Various Updates to standardize the UX and improve visual consistency.

2023-01-25 20:26 UTC, cedricwaxwing commented
@juliopavila Do you think you could help me with something here?

I'd like to add the ability to remove a permission from the permission view (in addition to the permission modal). Do you think you could add that functionality to the "x" buttons I've added here?

![image](https://user-images.githubusercontent.com/80348806/214681767-053f3fb5-34f8-40a6-89a6-fd4b4e4f6f6c.png)

2023-01-26 12:39 UTC, juliopavila commented
> @juliopavila Do you think you could help me with something here?
> 
> I'd like to add the ability to remove a permission from the permission view (in addition to the permission modal). Do you think you could add that functionality to the "x" buttons I've added here?
> 
> ![image](https://user-images.githubusercontent.com/80348806/214681767-053f3fb5-34f8-40a6-89a6-fd4b4e4f6f6c.png)

Yes sure!

2023-01-27 18:22 UTC, juliopavila commented on packages/app/src/components/views/publication/PermissionView.tsx
> +                ))} */}
remove old code

2023-01-27 18:22 UTC, juliopavila commented on packages/app/src/components/views/publication/PublicationView.tsx
> +                  // flexDirection: ["column", "row"],
remove old code

2023-01-27 18:22 UTC, juliopavila commented on packages/app/src/components/views/publication/PublicationView.tsx
> +                      /> */}
remove old code

2023-01-27 18:24 UTC, juliopavila requested changes
Great job, remove the old code and fix the build problem!

2023-01-29 22:34 UTC, juliopavila approved these changes

2023-01-30 16:37 UTC, merged