Editor block component
gnosis/tabula pull request #217
Opened 2023-02-08 17:35 UTC by juliopavila

Create editor block component

2023-02-27 20:00 UTC, cedricwaxwing commented on packages/app/src/components/views/publication/ArticleView.tsx
> +    <PublicationPage showCreatePost={false} showEditButton={true} publication={article?.publication}>
@juliopavila I hardcoded this as true for now, but it will need to be dynamic based on whether the user has edit permissions

2023-03-07 16:02 UTC, cedricwaxwing commented
Remaining bugs:

When we add an image in the rich text editor, it seems to make it impossible to add any other text. Also, it should be possible to select it with your cursor and click delete, like we can do for the text. (This is way lower priority though)
- [ ] When the "publish" is complete, it should take you to the article page automatically.
- [ ] I would like to add the captions for the thumbnail and rich text, but if this is complex, let's skip for now.
- [ ] If someone just posts an image, or images, it should still allow them to publish. Currently it stops and it says "Article Content is Required"
-  [ ] If you go back to publications after getting an error and click "New Post" again, it should not show the old error on the page.
- [ ] Clicking preview did not show the thumbnail I had added in the sidebar. It also removed my content from Article Content.
- [ ] For the loading state on the article page, we should add some text below the loader that says something like: "decrypting data from IPFS...please wait a moment"
- [ ] I tried uploading a 4MB thumbnail, and I think it breaks. We should maybe validate a max file size if this will break.

2023-05-09 12:27 UTC, manboy-eth reviewed
This looks amazing!

Some feedback:

- [ ]  The edit box pops up off-screen and can not be seen (if used on a not-very-wide screen):

<img width="300" alt="Screenshot 2023-05-09 at 13 38 43" src="https://github.com/gnosis/tabula/assets/2156509/5db31d50-d0f4-4956-a221-5fafea875e31"> Here the box is open, but can not be seen it's off-screen.
- [ ]   I don't know if it should be possible, but it's not possible to write `/h1` to convert the current component to an `h1` component.
- [ ]   If a text component (paragraph, code snippet, quote) is converted into an image or a divider component, it's no way to undo it; the text is lost `cmd-z` does not work then.
- [ ]   When an image component with an image is tuned into another component type, it's not possible to `cmd-z` back to the image.
- [ ]   When undoing, an empty component is kept for each line.
- [ ]   The thumbnail image is displayed at the top of the post and it's a thumbnail for the post. Perhaps we should rename it to "article image"?
<img width="858" alt="Screenshot 2023-05-09 at 13 54 19" src="https://github.com/gnosis/tabula/assets/2156509/55958dd4-9251-4281-8b22-5de120251fcd">

- [x]   When clicking the publication in the new edit page, the publicationId is used instead of the slug, this makes the URL transform from `http://localhost:3000/#/forplay.eth/...` into `http://localhost:3000/#/5-P-0x45207e251e415ee08d5b374f2f344b5ffa698d4b11ec7ac76f83a1c620a47a07-356/...`: 
<img width="870" alt="Screenshot 2023-05-09 at 14 02 37" src="https://github.com/gnosis/tabula/assets/2156509/fa2de670-3072-46ca-b7cb-8b5ac3e77d92">

- [ ]   No feedback when trying to publish without content or title. When clicking Publish, nothing happens.

2023-05-10 07:09 UTC, manboy-eth commented on packages/app/src/components/layout/ArticleHeader.tsx
> +          <Avatar width={31} height={31} publicationSlug={publication?.id} />
```suggestion
          <Avatar width={31} height={31} publicationSlug={publicationSlug ?? publication?.id} />
```

2023-05-10 07:11 UTC, manboy-eth commented on packages/app/src/components/layout/CreateArticlePage.tsx
> +        <meta property="og:url" content={`https://tabula.gg/#/${publication?.id}`} />
Should be publication slug

2023-05-10 07:17 UTC, manboy-eth commented on packages/app/src/components/layout/CreateArticlePage.tsx
> +  const { imageSrc } = usePublication(publication?.id || "")
Should use publication slug here

2023-05-10 07:18 UTC, manboy-eth commented on packages/app/src/components/views/publication/ArticleView.tsx
>    const publication = usePublication(article?.publication?.id || "")
Should use publication slug here

2023-05-10 07:27 UTC, manboy-eth reviewed
We can probably delete the old unused article creation views (`CreateArticleView2 `) now, right?

2023-05-10 07:29 UTC, manboy-eth commented on packages/app/src/components/views/publication/PublicationView.tsx
> +                      {publication.id}
```suggestion
                      {publicationSlug}
```

2023-05-10 07:30 UTC, manboy-eth commented on packages/app/src/constants/chain.ts
> +    return ArbitrumtIcon
```suggestion
    return ArbitrumIcon
```

2023-05-10 07:48 UTC, manboy-eth commented on packages/app/src/hooks/useIpfs.ts
> +export const IPFS_GATEWAY = process.env.REACT_APP_IPFS_GATEWAY
```suggestion
const IPFS_GATEWAY = process.env.REACT_APP_IPFS_GATEWAY
```
This should not be exported and never used directly. 
It's a fallback that will only be used if no IPFS node is provided by the user. 

We should strive to use the one provided by the user via the useIpfs hook. If, however, we require a URL for, for instance, getting an image, we should use the exported wrapper functions instead, like `getText` and `getImgSrc`, or create a new one if required.

FYI: `getImgSrc` is right now using the `IPFS_GATEWAY`, but this is a provisional workaround that will be fixed, so we should still use the `getImgSrc`.

2023-05-10 07:49 UTC, manboy-eth commented on packages/app/src/hooks/useMarkdown.tsx
> +      }
Update to not use IPFS_GATEWAY directly (see last comment)

2023-05-12 06:57 UTC, manboy-eth requested changes
Nice work! It seems that most things have been fixed.

However, there is still some stuff here that requires addressing: https://github.com/gnosis/tabula/pull/217#pullrequestreview-1418511427 (I added checkmarks to make it easy to see what's missing).

2023-06-02 15:14 UTC, manboy-eth reviewed
Nice, I can feel the performance improvements 🔥 

Some feedback:

- [ ] Links do not become clickable links in the preview or when published.

- [ ] When clicking edit on a published article, I get an error sample article: http://localhost:3000/#/forplay.eth/5-A-0x1e22ca9088459ce943a89f9c9d01b1cad0999af64cfed328749e7f54c6776907-78. 
<img width="1154" alt="Screenshot 2023-06-02 at 16 15 57" src="https://github.com/gnosis/tabula/assets/2156509/a46f1f82-0244-44b4-8b41-5b754c2f56f2">

- [ ] It looks like the edit article button in the article list is always disabled: 

<img width="961" alt="Screenshot 2023-06-02 at 16 17 00" src="https://github.com/gnosis/tabula/assets/2156509/9c74bfc4-727a-4260-a1ff-a7f34f501e87">

- [ ] The editor popup menu still does not show up on smaller screens (mobile); it is outside of view.

**New issues added 9. Jun**:
- [ ]  No articles can be opened from the article list.

- [ ] After entering the link, it's not possible to click enter, and if I click outside of the box, nothing happens (the link just disappears).

2023-06-28 11:43 UTC, manboy-eth requested changes
I see that most of the issues a fixed. However, I found two issues that needs to be fixed:

### Issue 1
When clicking the "Edit" button (both inside the article page and in the article list), I get this error, and the application freezes (I have to reload the page to make it interactive again): 
<img width="1079" alt="Screenshot 2023-06-28 at 13 25 14" src="https://github.com/gnosis/tabula/assets/2156509/8a5ec8bb-ff28-43b9-9362-948be8695b2b">
This is especially bad when writing an article since you will lose all your writing.

**Reproduce** 
1. Open the "article list" page or an article page.
2. Click the "Edit" button.

### Issue 2
The app freezes after some time and returns this error (I have to refresh the page to make it interactive again):
<img width="1080" alt="Screenshot 2023-06-28 at 13 28 11" src="https://github.com/gnosis/tabula/assets/2156509/2194b4ad-b10a-4765-b7ae-71d40925f507">
This is especially bad when writing an article since you will lose all your writing.

**Reproduce** 
1. Open the "article list" page, an article page, or the "create new article" page in the app.
2. Wait for a couple of minutes.
3. The error shows up in the console up, and the UI freezes.

2023-07-03 13:00 UTC, manboy-eth requested changes
Found one issue.

Publishing fails from the article's preview page. And when going back to edit, the article content is empty.

#### Reproduce:
1. Click edit on an article (for example, the `my article is cool` article in this publication: http://localhost:4000/#/5-P-0x45207e251e415ee08d5b374f2f344b5ffa698d4b11ec7ac76f83a1c620a47a07-356).
2. Click the Preview button.
3. In the Preview page, click the Publish button.
4. Nothing happens.
5. If you click the Edit button in the preview page, the content will be empty.

2023-07-06 02:01 UTC, juliopavila commented
> Found one issue.
> 
> Publishing fails from the article's preview page. And when going back to edit, the article content is empty.
> 
> #### Reproduce:
> 1. Click edit on an article (for example, the `my article is cool` article in this publication: http://localhost:4000/#/5-P-0x45207e251e415ee08d5b374f2f344b5ffa698d4b11ec7ac76f83a1c620a47a07-356).
> 2. Click the Preview button.
> 3. In the Preview page, click the Publish button.
> 4. Nothing happens.
> 5. If you click the Edit button in the preview page, the content will be empty.

@manboy-eth This is a workaround to the issue of generating a CID for IPFS content. We're now leveraging the Infura API when necessary, especially in cases where a public IPFS gateway fails to generate a CID.

I've introduced a new function called `uploadToInfura` that uploads a file or string content to IPFS via the Infura API. If the file is a string, the function converts it to a blob before making the API request. We've also set `pin=false` in the API request to avoid pinning the file by default.

For this function to work properly, we need to supply it with the Infura API Key and Secret. I've added the placeholders for these keys to our environment variables. Please update your `.env` file with your Infura API Key and Secret:

```plaintext
REACT_APP_INFURA_API_KEY=your_infura_api_key
REACT_APP_INFURA_API_KEY_SECRET=your_infura_api_key_secret
```

This new function is used in our `uploadContent` function as a fallback when the IPFS HTTP client fails to upload the content. This provides a reliable way to ensure our content gets uploaded to IPFS.

2023-07-06 12:51 UTC, asgeir-s approved these changes
Nice work @juliopavila 🚀

2023-07-06 13:05 UTC, merged