Integrate ENS Record Setting in UI
gnosis/tabula pull request #256
Opened 2023-09-26 01:07 UTC by juliopavila

## **Description**:

closes #253 

### Problem:
Currently, there's no direct way in the UI for users to set their ENS record. Users have to manually add their publication hash to their ENS record, as shown in the example: [ENS Domain Example](https://app.ens.domains/name/manboy.eth/details). While they can access it at `tabula.gg/#/yourCustomEns`, and the app will automatically detect the ENS, the process could be more streamlined.

### Solution:
This PR integrates the `multicall` and `setText` methods from the ENS contract directly into our UI. Users can now easily set their ENS record by adding a button within the publications section. This button will execute all the necessary logic and explain to the user about the underlying processes.

### Changes:
1. **App.tsx**: Imported `EnsProvider` from `./services/ens/context`.
2. **WalletBadge.tsx**: Made several modifications including importing `useEnsContext` and refactoring the logic.
3. **EnsModal.tsx**: New component to handle the ENS modal UI.
4. **SettingSection.tsx**: Added logic to link the publication to the user's ENS name.
5. **ens.context.tsx**: New context for ENS operations.
6. **useEns.ts**: New hook to handle ENS-related operations.

### Additional Context:
The goal of this PR is to enhance the user experience by simplifying the setting of ENS records and clarifying what happens in the background.

---

### **Reviewer Checklist**:
- [ ] Code is clean and follows the project's coding standards.
- [ ] Functionality has been verified and is working as intended.
- [ ] UI/UX is intuitive and matches the design specs.
- [ ] All new dependencies have been declared.
- [ ] PR is linked to the related issue.

### **Screenshots**

<img width="1688" alt="image" src="https://github.com/gnosis/tabula/assets/19823989/03d649e8-f340-48de-b24e-6cf298e4eb71">
<img width="1680" alt="image" src="https://github.com/gnosis/tabula/assets/19823989/78f02eeb-f0f9-46fa-9f3f-010320408b2a">
<img width="1701" alt="image" src="https://github.com/gnosis/tabula/assets/19823989/a17a102a-8176-4068-864e-16389915fd28">

2023-09-26 03:23 UTC, auryn-macmillan commented
Checked out the deploy preview, but it's not showing the new elements to set ENS names.
![image](https://github.com/gnosis/tabula/assets/8453294/ecfd8e59-c0a3-4443-9772-53a58ce1e9c4)

2023-09-28 12:08 UTC, manboy-eth reviewed
Nice work, just one note:
We will probably need some way of getting the user to change chain to mainnet, if they are not already on mainnet, since the ENS record is always set on mainnet.

2023-09-28 17:15 UTC, manboy-eth commented on packages/app/src/services/ens/hooks/useENS.ts
> +  )
Why do we do a 'multicall' when we are only doing one call?

2023-09-28 17:23 UTC, cedricwaxwing approved these changes
LGTM, nice work Julio!

2023-10-08 22:11 UTC, juliopavila commented
Thanks, for your feedback @manboy-eth, I already applied the following changes:

- Changed default to mainnet subgraph, the only "real" ENS registry, as per your suggestion.
- Replaced 'multicall' with 'setText' for a single call operation, cleaned up the code, and tested functionality.

Please review

2023-10-09 14:08 UTC, manboy-eth reviewed
Nice, much better :)

But did you do anything to handle this?
> We will probably need some way of getting the user to change chain to mainnet, if they are not already on mainnet, since the ENS record is always set on mainnet.

When the user for instance has a publication on Gnosis Chain, the user must still set the ENS record on mainnet.

2023-10-11 08:00 UTC, manboy-eth requested changes
Excellent, now we just need some minor changes and I think this is ready to merge.

2023-10-11 08:00 UTC, manboy-eth commented on packages/app/src/components/commons/NetworkModal.tsx
> +const NetworkModal: React.FC<any> = ({ open, handleClose }) => {
Missing props type.

2023-10-11 08:00 UTC, manboy-eth commented on packages/app/src/components/commons/NetworkModal.tsx
> +        handleClose({}, "escapeKeyDown")
Used as MUIs `onClose` ModalProp, but looks like it is actually a `() => void` (from component usage in `packages/app/src/components/views/publication/components/SettingSection.tsx`).

2023-10-11 14:17 UTC, merged